---
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "ReferenceIssue"
paths:
  /empty:
    get:
      summary: "Empty operation that does nothing."
      description: |
        Swagger Editor requires at least one path to consider a description file as valid.
        Having this empty operation allows this file to be loaded into Swagger Editor to
        check for syntax violations.
      responses:
        200:
          description: "No response."
components:
  schemas:
    Person:
      type: object
      description: A simple definition of a person.
      required:
      - firstName
      - lastName
      properties:
        firstName:
          type: string
          example: Stan
        lastName:
          type: string
          example: Smith
